/* Note:
-- YOU MUST REINPUT ALL FROM DATA MASTER MENU MANUALLY after RUNNING THIS QUERY 
--
*/

USE webspp;
DELETE FROM angkatan;
DELETE FROM kelas;
DELETE FROM pembayaran;
DELETE FROM siswa;
DELETE FROM tahun;